dj_admin/urls.py
from django.urls import path
from dj_admin import views 

urlpatterns = [
    path('',views.loginAdmin,name="admin"),
    path('logoutadmin',views.logoutAdmin,name="logoutadmin"),
    path('starter/', views.starter,name='starter'),
    path('admins/' , views.showAdmins,name='admins'),
    path('promote/<id>',views.promoteUser,name="promote"),
    path('lock/<id>',views.lockUser,name="lock"),
    path('unlock/<id>',views.unlockUser,name="unlock"),
    path('categories/',views.showCategory,name="category"),
    path('categoryform/', views.addCategory,name="addcategory"),
    path('deletecat/<cat_id>', views.deleteCategory,name="deletecat"),
    path('editcat/<cat_id>', views.editCategory,name="editcat"),
    path('posts/',views.showPosts,name="post"),
    path('postform/', views.addPost,name="addpost"),
    path('deletepost/<post_id>', views.deletePost,name="deletepost"),
    path('editpost/<post_id>', views.editPost,name="editpost"),
    path('forbiddenwords/', views.showForbidden,name="forbiddenwords"),
    path('forbiddenwordform/', views.addForbidden,name="addforbiddenwords"),
    path('delforbidden/<word_id>', views.delForbidden,name="delforbiddenwords"),
    path('editforbidden/<word_id>', views.editForbidden,name="editforbiddenwords"),
    
]

djproj/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('dj_admin/', include('dj_admin.urls')),
    path('admin/', admin.site.urls),
    path('dj_blog/', include('dj_blog.urls')),
]

dj_admin/models.py
from django.db import models

# Create your models here.

dj_blog/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
# Account model extends from User (built-in-Model) and add some extra fields
class Account(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(default='images/default.png',upload_to = 'Avatars/')
    is_locked = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

# Category Model
class Category(models.Model):
    cat_name=models.CharField(max_length=100)
    user = models.ManyToManyField(User,related_name='categories')

    def __str__(self):
        return self.cat_name

# Tags Model
class PostTags(models.Model):
    tag_name = models.CharField(max_length=100)

    def __str__(self):
        return self.tag_name

# Post Model    
class Post(models.Model):
    title = models.CharField(max_length=50)
    picture = models.ImageField(null=True,upload_to='images/')
    content = models.CharField(max_length=255)
    likes = models.ManyToManyField(User,blank=True,related_name='likes')
    dislikes = models.ManyToManyField(User,blank=True,related_name='dislikes')
    date_of_publish = models.DateTimeField(auto_now_add=True,null=True,blank=True)
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    category = models.ForeignKey(Category,on_delete=models.CASCADE)
    tag = models.ManyToManyField(PostTags,blank=True)
      
    def __str__(self):
        return self.title

# Comment Model    
class Comment(models.Model):
    comment_body=models.CharField(max_length=100)
    comment_time=models.DateTimeField(auto_now_add=True,null=True,blank=True)
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    post_id=models.ForeignKey(Post,on_delete=models.CASCADE,related_name="comments") 
    parent = models.ForeignKey('self', on_delete=models.CASCADE, blank=True, null=True, related_name='+') #Parent to hold comment id

    def __str__(self):
        return self.user.username
    
# Reply Model  
class Reply(models.Model):
    reply_body=models.CharField(max_length=100)
    reply_time=models.TimeField(null=True)
    user_id=models.ForeignKey(User, on_delete=models.CASCADE)
    comment_id=models.ForeignKey(Comment, on_delete=models.CASCADE)


class ForbiddenWords(models.Model):
    forbidden_word=models.CharField(max_length=100)

    def __str__(self):
        return self.forbidden_word    

dj_admin/forms.py
from django.contrib.auth.forms import AuthenticationForm ,UsernameField
from django import forms

class LoginAdmin(AuthenticationForm): 
    username = UsernameField( widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Username..'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password...'}))

dj_admin/views.py
from django.contrib import messages
from django.shortcuts import render,redirect
from django.contrib.auth.models import User
from dj_admin.forms import LoginAdmin
from dj_blog.models import *
from dj_blog.forms import *
from django.contrib.auth import login, logout, authenticate
from django.contrib.admin.views.decorators import staff_member_required
from .forms import LoginAdmin

# Create your views here.
# function to allow the admins to login in admin panel
def loginAdmin(request):
    login_form = LoginAdmin()
    if request.method == "POST":
            login_form = LoginAdmin(data=request.POST)
            # checking if the login form is valid or not 
            if(login_form.is_valid()):
                # get the data for username and password from the post request then checking if they exists in the database  
                username = request.POST['username']
                password = request.POST["password"]
                user = authenticate(username=username, password=password)
                if user is not None :
                    if user.is_staff :
                        login(request,user)
                        if request.GET.get('next') is not None:
                            return redirect(request.GET.get('next'))
                        else:
                            return redirect('starter')
                    else : 
                        messages.info(request,"This Page is only for admins ")
    context = {"login_form": login_form}
    return render(request, 'dj_admin/loginadmin.html', context)

#function to allow the admins to logout from the panel 
def logoutAdmin(request):
    logout(request)
    return redirect("admin")

# this is the starter page for the admin page

@staff_member_required(login_url="admin")
def starter(request):
    # get all normal users 
    users = User.objects.filter(is_staff= False) 
    context={'users':users}
    return render(request,'dj_admin/starter.html',context)

# view to promote the user to an admin 
def promoteUser(request,id):
    user=User.objects.get(id = id)
    #check if the user is not blocked he can be promoted .. and that's by making the is_staff attribute and is_superuser equal true 
    if not islocked(user):
        user.is_staff=True
        user.is_superuser=True
        user.save()
        return redirect('starter')
    else : 
        return redirect('starter')

# view to show the all the admins 
@staff_member_required(login_url="admin")
def showAdmins(request):
    admins=User.objects.filter(is_staff = True , is_superuser=True)
    context={'admins':admins}
    return render(request,'dj_admin/admins.html',context)

# lock the required account first then lock the user associated to that account
def lock_user(user):
        account = Account.objects.get(user=user)
        account.is_locked = True
        account.save()

@staff_member_required(login_url="admin")
def lockUser(request,id):
    user = User.objects.get(id=id)
    lock_user(user)
    return redirect('starter')

# unlock the required account first then unlock the user associated to that account 
def unlock_user(user):
        account = Account.objects.get(user=user)
        account.is_locked = False
        account.save()

@staff_member_required(login_url="admin")
def unlockUser(request,id):
    user = User.objects.get(id=id)
    unlock_user(user)
    return redirect('starter')

# function to return the status of the account if it is locked or not 
def islocked(user):
    return user.account.is_locked

# view to show the catagories 
@staff_member_required(login_url="admin")
def showCategory(request):
    categories = Category.objects.all()
    context = {'categories':categories}
    return render(request,'dj_admin/categories.html',context)

# add category 
@staff_member_required(login_url="admin")
def addCategory(request):
    # create catageory form 
    form = CategoryForm()
    if request.method == 'POST':
        form = CategoryForm(request.POST)
        # checking the form if it's valid or not 
        if form.is_valid():
            form.save()
            return redirect("category")
    context = {"cat_form": form}
    return render(request, "dj_admin/categoryform.html", context)

# delete category 
@staff_member_required(login_url="admin")
def deleteCategory(request,cat_id):
    category= Category.objects.get(id=cat_id)
    category.delete()
    return redirect("category")

@staff_member_required(login_url="admin")
def editCategory(request,cat_id):
    category = Category.objects.get(id= cat_id)
    # put the category object which we want to edit into the form method by assigning it to the instance attribute 
    form = CategoryForm(instance=category)
    if request.method == 'POST':
        form = CategoryForm(request.POST,instance=category)
        if form.is_valid():
            form.save()
            return redirect('category')
    context = {"cat_form":form}
    return render (request,"dj_admin/editcategory.html",context)


@staff_member_required(login_url="admin")
def showPosts(request):
    posts = Post.objects.all()
    context = {'posts':posts}
    return render(request,'dj_admin/posts.html',context)

@staff_member_required(login_url="admin")
def addPost(request):
    # get the forms empty to be filled
    post_form = PostForm()
    tag_form = TagsForm()
    
    # if the add button pressed save the input data after validation
    if request.method == 'POST':
        post_form = PostForm(request.POST,request.FILES)
        tag_form = TagsForm(request.POST)
        if post_form.is_valid() and tag_form.is_valid():
            obj = post_form.save(commit=False)
            obj.user = request.user
            obj.save()
            
            # get object from tag before saving it
            tag_obj = tag_form.save(commit=False)
            # split the separated tags by comma
            splitted_tags = str(tag_obj).split(',') 
            # loop on each tag splitted, add to the related post and save it
            for tag in splitted_tags:
                newTag = PostTags.objects.create(tag_name = tag)
                newTag.save()
                obj.tag.add(newTag)
                
            obj.save()
            return redirect('post')

    context = {'post_form':post_form,'tag_form':tag_form}
    return render(request,'dj_admin/postform.html',context)


#view to edit specific forbidden word using the word id
@staff_member_required(login_url="admin") 
def editPost(request,post_id):
    # get the post with its saved data
    post = Post.objects.get(id= post_id)
    tags = post.tag.all()
    post_form = PostForm(instance=post)
    # get empty form for new tags
    tag_form = TagsForm()
    
    context = {}
    context['post_form'] = post_form
    context['tag_form'] = tag_form
    
    if request.method == 'POST':
        # get the new editted data
        post_form = PostForm(request.POST,request.FILES,instance=post)
        tag_form = TagsForm(request.POST)
        if post_form.is_valid():
            obj = post_form.save(commit = False)
            obj.user = request.user
            # remove the old tags to be replaced with the new editted tags
            obj.tag.clear()
            obj.save()
            # get the editted tags
            tags = post_form.cleaned_data['tag']
            
            for tag in tags:
                newTag = PostTags.objects.get(tag_name = tag)
                #add the tags to related post
                obj.tag.add(newTag)
                obj.save()
            
            tag_obj = request.POST.get('tag_name')
            splitted_tags = str(tag_obj).split(',')
            
            all_tags = PostTags.objects.all()
            is_exist = False
            
            # check if the splitted is empty to validate the input of user
            if splitted_tags[0] != '':
                for tag in splitted_tags:
                    for compare in all_tags:
                        print(tag,compare)
                        if str(tag) == str(compare):    
                            is_exist = True
                            
                    if not is_exist:
                        newTag = PostTags.objects.create(tag_name = tag)
                    newTag.save()
                    obj.tag.add(newTag)
                    is_exist = False
            obj.save()
            return redirect('post')
 
    return render (request,"dj_admin/editpost.html",context)

@staff_member_required(login_url="admin")
def deletePost(request,post_id):
    post = Post.objects.get(id=post_id)
    post.delete()
    return redirect("post")

# view to add the forbidden words in admin page 
@staff_member_required(login_url="admin")
def addForbidden(request):
    form = ForbiddenWordsForm()
    if request.method == 'POST':
        form = ForbiddenWordsForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("forbiddenwords")
    context = {"word_form": form}
    return render(request, "dj_admin/forbiddenwordform.html", context)


# view to show all the forbidden words 
@staff_member_required(login_url="admin")
def showForbidden(request):
    forbidden_words = ForbiddenWords.objects.all()
    context = {'forbidden_words' : forbidden_words}
    return render(request, "dj_admin/forbiddenwords.html", context)

# view to delete specific forbidden word using the word id
@staff_member_required(login_url="admin")
def delForbidden(request,word_id):
    forbidden_words = ForbiddenWords.objects.get(id = word_id)
    forbidden_words.delete()
    return redirect('forbiddenwords')

#view to edit specific forbidden word using the word id 
@staff_member_required(login_url="admin")
def editForbidden(request,word_id):
    forbidden_words = ForbiddenWords.objects.get(id= word_id)
    form = ForbiddenWordsForm(instance=forbidden_words)
    if request.method == 'POST':
        form = ForbiddenWordsForm(request.POST,instance=forbidden_words)
        if form.is_valid():
            form.save()

templates/dj_admin/admins.html
{% extends 'dj_admin/base_layout.html' %}

{% block content %}

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid bg-dark shadow-lg p-2">
        <div class="row mb-2">
          <div class="col-sm-12">
            <h1 class="text-center text-light fw-light">Admins Info</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <div class="container-fluid">
      <div class="row">
        <div class="col md-12 sm-6">
        <table style="text-align : center;" class="table table-lg table-dark">
          <thead>
            <tr>
              <!-- Admin Table Structure -->
              <th scope="col">ID</th>
              <th scope="col">Username</th>
              <th scope="col">Email Address</th>
              <th scope="col">Last login</th>
            </tr>
          </thead>
          <tbody>
            <!-- Put all admin details in the table -->
            {% for admin in admins %}
           <tr style="background-color:	#5DBCD2">
           <td>{{admin.id}}</td>
           <td>{{admin.username}}</td>
           <td>{{admin.email}}</td>
           <td>{{admin.last_login}}</td>
           <td style="background-color:	#5DBCD2" colspan="5" style="text-align:center; padding:15px;"></td>          </tr> 
          {%endfor%}
          </tbody>
        </table>
        </div>
      </div>
    </div>
  {% endblock %}

templates/dj_admin/base_layout.html
{% load static %}

<!DOCTYPE html>
<!--
This is a base layout template page. Use this page to start your new project from
scratch. This page gets rid of all links and provides the needed markup only.
-->
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Blog Admin</title>
  <link
      href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.1.0/css/bootstrap.min.css"
      rel="stylesheet"
    />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css"
    />
    <link
      href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-tagsinput/0.8.0/bootstrap-tagsinput.css"
      rel="stylesheet"
    />
  <!-- Font Awesome Icons -->
  <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href=" {% static 'dist/css/adminlte.min.css' %}">
</head>
<body class="hold-transition sidebar-mini">
  
  <style type="text/css">
    .bootstrap-tagsinput .tag {
      margin-right: 2px;
      color: white !important;
      background-color: #0d6efd;
      padding: 0.2rem;
    }
  </style>

<div class="wrapper">

  <!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="/dj_blog/landing" class="nav-link">Our Blog</a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="/dj_admin/admins" class="nav-link">Admins</a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="{% url 'logoutadmin' %}" class="nav-link">Logout</a>
      </li>
    </ul>
  </nav>
    
  <!-- Main Sidebar Container -->
  <aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="/dj_blog/landing.html" class="brand-link">
      <img src="{% static 'dist/img/Admin.jpeg' %}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
      <span class="brand-text font-weight-light">Django Admin </span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user panel (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="info">
          <a href="#" class="d-block">Dashboard </a>
        </div>
      </div>

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
          <li class="nav-item menu-open">
            <a href="#" class="nav-link active">
              <i class="nav-icon fas fa-tachometer-alt"></i>
              <p>
                Provided Links
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="/dj_admin/starter" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Users</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="/dj_admin/forbiddenwords" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>ForbiddenWords</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="/dj_admin/categories" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Categories</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="/dj_admin/posts" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Posts</p>
                </a>
              </li>
            </ul>
          </li>
        </ul>
        
        
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>
  
  {% block content %}
  {% endblock %}




  <div class="content">
      <div class="container-fluid">
          <!-- /.col-md-6 -->
        </div>
        <!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
    <div class="p-3">
      <h5>Title</h5>
      <p>Sidebar content</p>
    </div>
  </aside>
  <!-- /.control-sidebar -->

  <!-- Main Footer -->
  <footer class="main-footer">
    <!-- To the right -->
    <div class="float-right d-none d-sm-inline">
      Anything you want
    </div>
    <!-- Default to the left -->
    <strong>Copyright &copy; 2022 <a href="https://adminlte.io">SONSZ-BLOG</a>.</strong> All rights reserved.
  </footer>
</div>
<!-- ./wrapper -->

<!-- REQUIRED SCRIPTS -->

<!-- jQuery -->
<script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'dist/js/adminlte.min.js' %}"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.1.0/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-tagsinput/0.8.0/bootstrap-tagsinput.min.js"></script>

</body>
</html>

templates/dj_admin/categories.html
{% extends 'dj_admin/base_layout.html' %}

{% block content %}
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-12">
            <h1 class="text-center shadow p-3 mb-2 text-light bg-dark fw-light">Categories</h1>
            <br>
            <div>
              <center>
                <a class="btn btn-dark"  href="/dj_admin/categoryform">Add Category</a>
              </center>
            </div>
          </div><!-- /.col -->
          <div class="col-sm-6">
          </div>
        </div>
      </div>
    </div>
   

    <!-- Main content -->
    <div class="container-fluid">
      <div class="row">
        <div class="col-12 md-6 sm-6">
        <table style="text-align : center;" class="table table-lg table-dark">
          <thead>
            <tr>
              <th class="col-6" scope="col">Categories</th>
              <th class="col-6" scope="col" colspan="3">Actions</th>
            </tr>
          </thead>
          <tbody>
            <!-- Put all the catagories in the table  -->
            {% for category in categories %}
           <tr style="background-color:	#636e72">
           <td>{{category.cat_name}}</td>
           <td style="background-color:	#636e72" colspan="5" style="text-align:center; padding:15px;">
            <!-- Two Buttons For Delete and Edit catagories -->
           <a class="btn" style="background-color: #ffc507; " href="/dj_admin/deletecat/{{ category.id }}">Delete</a>
           <a class="btn" style="background-color: #ffc507; " href="/dj_admin/editcat/{{ category.id }}">Edit</a>
           </td>         
          </tr> 
          {%endfor%}
          </tbody>
        </table>
        </div>
      </div>
    </div>

    {% endblock %}

templates/dj_admin/categoryform.html
{% extends 'dj_admin/base_layout.html' %}

{% block content %}
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid bg-dark shadow-lg p-2">
        <div class="row ">
          <div class="col-sm-12">
            <h1 class="text-center text-ligh fw-light">Categories Creation</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
          </div>
        </div>
      </div>
    </div>
   

    <!-- Main content -->
    <div class="container-fluid">
      <div class="row">
        <div class="col-8 md-8 sm-8">
          <!-- Start category form -->
            <form method="POST" action=""> 
                {% csrf_token %}
                <div class="input-group mb-3 col-6">
                    <label class="col-6" >Category Name </label>
                     <span class="col-2">{{ cat_form.cat_name }}</span>
                </div>
                <div>
                    <input class="btn btn-dark" type="submit" value="Submit">
                </div>
            </form>
            <div>
              <!-- Handling the category form errors  -->
                {% for field, errors in cat_form.errors.items %}
                               {% for error in errors %}
                               <p class="text-danger">{{ error }}</p>
                               {% endfor %}
                        {% endfor %}
            </div>
        </div>
        </div>
      </div>
    </div>

{% endblock %}

templates/dj_admin/editcategory.html
{% extends 'dj_admin/base_layout.html' %}

{% block content %}

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid bg-dark shadow-lg p-2">
        <div class="row">
          <div class="col-sm-12">
            <h1 class="text-center text-ligh fw-light">Edit Category</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
          </div>
        </div>
      </div>
    </div>
   
    <!-- Main content -->
    <div class="container-fluid">
      <div class="row">
        <div class="col-8 md-8 sm-8">
          <!-- Start Edit category form -->
            <form method="POST" action=""> 
                {% csrf_token %}
                <div class="input-group mb-3 col-6">
                    <label class="col-6" >Category Name</label>
                     <span class="col-2">{{ cat_form.cat_name }}</span>
                </div>
                <div>
                    <input class="btn btn-dark" type="submit" value="Submit">
                </div>
            </form>
            <div>
              <!-- Handling the category form errors  -->
                {% for field, errors in cat_form.errors.items %}
                    {% for error in errors %}
                      <p class="text-danger">{{ error }}</p>
                    {% endfor %} 
                {% endfor %}
            </div>
        </div>
        </div>
      </div>
    </div>
{% endblock %}

templates/dj_admin/editforbiddenwords.html
{% extends 'dj_admin/base_layout.html' %}

{% block content %}

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid ">
        <div class="row">
          <div class="col-sm-12">
            <h1 class="text-center shadow p-2 text-light bg-dark fw-light">Edit Forbidden Words</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
          </div>
        </div>
      </div>
    </div>
   

    <!-- Main content -->
    <div class="container-fluid">
      <div class="row">
        <div class="col-8 md-8 sm-8">
          <!-- Start edit forbidden words list -->
            <form method="POST" action=""> 
                {% csrf_token %}
                <div class="input-group mb-3 col-6">
                    <label class="col-4" >Forbidden Word</label>
                     <span class="col-2" >{{ word_form.forbidden_word }}</span>
                </div>
                <div>
                    <input class="btn btn-dark" type="submit" value="Submit">
                </div>
            </form>
            <div>
              <!-- Handling the forbidden word form errors  -->
                {% for field, errors in word_form.errors.items %}
                               {% for error in errors %}
                               <p class="text-danger">{{ error }}</p>
                               {% endfor %}
                        {% endfor %}
            </div>
        </div>
        </div>
      </div>
    </div>
{% endblock %}

templates/dj_admin/editpost.html
{% extends 'dj_admin/base_layout.html' %}

{% block content %}

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid bg-dark shadow-lg p-2">
        <div class="row">
          <div class="col-sm-12">
            <h1 class="text-center text-ligh fw-light">Edit Post</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
          </div>
        </div>
      </div>
    </div>
   

    <!-- Main content -->
    <div class="container-fluid">
      <div class="row shadow p-3 mb-4 ">
        <div class="col-8 md-8 sm-8">
          <!-- Start edit post form -->
            <form method="POST" enctype="multipart/form-data"> 
                {% csrf_token %}
                <div class="mb-3 col-12 shadow p-3 mb-4" style="margin-left: 20%;">
                  <label class="form-label col-12">{{post_form.title.label}} {{post_form.title}}</label>
                  <label class="form-label col-12">{{post_form.picture.label}} {{post_form.picture}}</label>
                  <label class="form-label col-12">{{post_form.content.label}} {{post_form.content}}</label>
                  <label class="form-label col-12">{{post_form.category.label}} {{post_form.category}}</label>
                  <label class="form-label col-12">{{post_form.tag.label}} {{post_form.tag}}</label>
                    <!-- {{ post_form.as_p }} -->
                    <label class="form-label col-12">Tag Name:</label>
                    <input type="text" name="tag_name" class="form-control" data-role="tagsinput" maxlength="100" id="id_tag_name" style="display: none;">
                </div>
                <div style="margin-left: 20%;">
                    <input class="btn btn-dark" type="submit" value="Submit">
                </div>
            </form>
            <div>
                {% for field, errors in post_form.errors.items %}
                    {% for error in errors %}
                        <p class="text-danger">{{ error }}</p>
                    {% endfor %} 
                {% endfor %}
            </div>
        </div>
        </div>
      </div>
    </div>
{% endblock %}